monitor.alsa.enabled = true


monitor.alsa.rules = [
  # Your Topping DX3 Pro rule (regex match uses "~")
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Topping_DX3_Pro_-00.*"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S32LE"
        audio.allowed-rates = "44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000"
      }
    }
  }
]

