[colors]
draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#5c6370"
# blue = "#61afef"
# cyan = "#56b6c2"
# green = "#98c379"
# magenta = "#c678dd"
# red = "#e06c75"
# white = "#ECEFF4"
# yellow = "#d19a66"

# [colors.normal]
# black = "#3B4252"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B48EAD"
# red = "#BF616A"
# white = "#abb2bf"
# yellow = "#EBCB8B"

[colors.primary]
background = "#1e2127"
foreground = "#D8DEE9"


[font]
size = 9
# family = "MonaspiceNe Nerd Font"
# size = 12

[font.bold]
# family = "Monaspace Neon"
family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Monaspace Neon"
family = "MonaspiceNe Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Monaspace Neon"
family = "MonaspiceNe Nerd Font"
style = "Italic"

[font.normal]
# family = "Monaspace Neon"
family = "MonaspiceNe Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 1.0
# opacity = 0.99

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
import = [
    "/home/daniel.lin/.config/alacritty/themes/themes/nord.toml"
]

